@api = https://localhost:5001

### add post
POST {{api}}/post
Content-Type: application/json

{
"title":  "Mielony",
"description": "Tradycyjne danie",
"categoryId": "e98f8ec1-6b9e-40d8-85f3-99347f6f61aa",
"userId": "A4203D0D-A4F5-4650-8CF2-F37F6E771C70",
"tags":["557ce82e-c6c7-4ed2-9ef3-5d8ecf2bfbb3"]
}

### update post
PUT {{api}}/post/6785107c-c68c-4050-abd6-d4a63e0bfc81
Content-Type: application/json

{
"title":  "Mielony",
"description": "Tradycyjne danie",
"categoryId": "e98f8ec1-6b9e-40d8-85f3-99347f6f61aa",
"userId": "A4203D0D-A4F5-4650-8CF2-F37F6E771C70",
"tags":["6986edae-5428-449b-aa7c-110f3753b701"]
}

### get post id
GET {{api}}/post/6785107c-c68c-4050-abd6-d4a63e0bfc81
Content-Type: application/json

### get posts
GET {{api}}/posts
Content-Type: application/json

### delete post
DELETE {{api}}/post/8CE9C508-054F-4D77-9EC7-0413FF2A9129
Content-Type: application/json
