# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - webappblogti

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://blogapiti.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_81b61a95da7946d7960f70851f861ffc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_51dafc90374247e48d5f2f8955e691c6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: blogapiti.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_81b61a95da7946d7960f70851f861ffc }}/cookblog.api:${{ github.sha }}
        file: ./../src/CookBlog/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webappblogti'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_69143c1befc64518a63534a585efecb8 }}
        images: 'blogapiti.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_81b61a95da7946d7960f70851f861ffc }}/cookblog.api:${{ github.sha }}'
